version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: food-market-app
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel

  web:
    image: nginx:alpine
    container_name: food-market-nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    depends_on:
      - app
    platform: linux/amd64

  db:
    image: mysql:5.7
    container_name: food-market-db
    environment:
      MYSQL_ROOT_PASSWORD: root  # Only root password needed
      MYSQL_DATABASE: laravel
    ports:
      - "3306:3306"
    networks:
      - laravel
    platform: linux/amd64

networks:
  laravel:
    driver: bridge
